import {initialState,transition,evidence} from './borrowed-voice-model.mjs';
const $=id=>document.getElementById(id);let state=initialState();
const voice=text=>`<blockquote><span>ORYN / QUIET CHANNEL</span><p>“${text}”</p></blockquote>`;
const option=(action,title,detail)=>`<button class="choice" data-action="${action}"><strong>${title}</strong><span>${detail}</span><b aria-hidden="true">↗</b></button>`;
const message=()=>`<div class="transmission"><div class="message-label">SIMULATED MESSAGE / UNVERIFIED SENDER</div><div class="sender"><span class="sigil" aria-hidden="true">◇</span><div><strong>Command Allocation Desk</strong><small>Claims to speak for Admiral Voss</small></div></div><h2>“Your crew has been selected.”</h2><p class="quote">Send 40 credits now. Receive 80 tomorrow. Admiral Voss has approved your place personally.</p><p>“Thousands of crews have already joined. Your allocation expires soon. Reply here if you need confirmation.”</p><p class="fine">A familiar seal and screenshots of successful payments accompany the message.</p></div>`;
function content(){
 const s=state;
 if(s.step==='intro')return `<div class="eyebrow">A DEEPER MISSION · ABOUT 6–10 MINUTES</div><h1 id="scene-title" tabindex="-1">The borrowed<br><em>voice.</em></h1><p class="lead">The message knows the right names. It uses the right seal. It sounds like someone you trust.</p><div class="panorama"><img src="assets/first-contact.png" alt="Oryn and the other four Federation guides against a star field."></div>${voice('A familiar voice can be borrowed. Before we follow it, let’s find out where it actually comes from.')}<p>Your crew is docked at the relay station with <strong>100 fictional credits</strong>. A private transmission offers a place in a special allocation. You can investigate in any order, decline, wait, or see what happens if you send credits.</p><div class="brief"><strong>Your mission</strong><span>Separate what the sender claims from what an independent source can establish. If a choice goes wrong, the story continues.</span></div><button class="primary" data-action="begin">Open the transmission →</button>`;
 if(s.step==='inbox')return `<div class="eyebrow">01 / THE INVITATION</div><h1 id="scene-title" tabindex="-1">It sounds<br>like Command.</h1>${message()}${voice('We have an invitation. We do not yet have a verified sender. Those are different things.')}<div class="actions"><button class="primary" data-action="investigate">Investigate the message →</button><button class="secondary" data-action="decide">Make a decision now</button></div><p class="fine">No timer is running. The deadline is part of the fictional sender's pressure. Take as long as you need.</p>`;
 if(s.step==='investigate')return `<div class="eyebrow">02 / FOLLOW THE SOURCE</div><h1 id="scene-title" tabindex="-1">A claim is<br>a starting point.</h1><p class="lead">Choose what to check. Your notebook keeps each finding. There is no required order and no reward for opening more cards.</p><div class="evidence-grid">${Object.entries(evidence).map(([key,e])=>`<button class="choice" data-action="${key}" aria-pressed="${s.active===key}"><strong>${e.title}</strong><span>${s.opened.includes(key)?'Checked · open again':'Open this inquiry'}</span><b aria-hidden="true">↗</b></button>`).join('')}</div>${s.active?`<section class="evidence-result" aria-labelledby="finding-title"><div class="source-label">${evidence[s.active].kind}</div><h2 id="finding-title" tabindex="-1">${evidence[s.active].title}</h2><p>${evidence[s.active].text}</p><p>${evidence[s.active].note}</p></section>`:voice('Ask not only what a message says, but who is in a position to know.')}<button class="primary" data-action="decide">Choose your next move →</button><p class="fine">All inquiries happen inside the story. No real organization is contacted.</p>`;
 if(s.step==='decide')return `<div class="eyebrow">03 / KEEP THE CHOICE YOURS</div><h1 id="scene-title" tabindex="-1">Another message.<br>More pressure.</h1><div class="pressure">“Last chance. If you keep asking questions, we will give your place to another crew.”<small>Simulated pressure. There is still no real countdown.</small></div><p class="lead">${s.opened.includes('directory')?'The independently contacted duty officer already said Command did not authorize this offer. The new deadline does not change that finding.':'You have not independently verified the sender. A shorter deadline does not supply the missing evidence.'}</p>${voice('You can stop without winning an argument. You can wait without promising to return. Curiosity is not a debt you owe the sender.')}<div class="choices">${option('hold','Set the message aside','Send nothing. Keep 100 credits. Leave the offer unresolved rather than assuming it is safe.')}${option('decline','Decline and close the channel','Send nothing. Keep 100 credits. End contact with this sender.')}${option('send','Simulate sending 40 credits','Continue the fictional story with 60 credits. No real payment occurs.')}</div><button class="secondary" data-action="recheck">Return to the evidence</button>`;
 if(s.step==='aftermath')return `<div class="eyebrow">04 / AFTER THE CHOICE</div><h1 id="scene-title" tabindex="-1">Tomorrow arrives.<br>The payment doesn't.</h1><p class="lead">The sender disappears. You sent 40 fictional credits, the promised 80 never arrives, and your crew has <strong>60 left</strong>.</p>${voice('Being deceived does not make you foolish. The message was built to rush you. Our next decision still matters.')}<p>A new sender appears. It says it knows about the loss and can recover everything. Your crew wants to read it.</p><div class="actions"><button class="primary" data-action="read-followup">Read the follow-up →</button><button class="secondary" data-action="stop">Stop contact now</button></div><p class="fine">The story identifies the first message as an impersonation scam. No recovery has happened.</p>`;
 if(s.step==='recovery')return `<div class="eyebrow">05 / A SECOND PROMISE</div><h1 id="scene-title" tabindex="-1">“We can get<br>your credits back.”</h1><div class="transmission"><div class="message-label">SIMULATED MESSAGE / NEW UNVERIFIED SENDER</div><h2>From: Relay Recovery Bureau</h2><p class="quote">We traced your lost 40 credits. Send a 20-credit release fee and we will return the original amount immediately.</p><p>The message includes the exact amount you lost. It offers no independent proof of control over those credits.</p></div>${voice('Knowing what happened to you is not the same as being able to fix it. A second promise deserves its own check.')}<div class="choices">${option('record','Save the details and stop contact','Make a fictional incident note. Keep 60 credits. No real report is sent and no money is restored.')}${option('stop','Close this channel too','Keep 60 credits. End contact without another payment.')}${option('pay-recovery','Simulate paying the 20-credit fee','See what happens next with 40 credits remaining. No real payment occurs.')}</div>`;
 const loss=100-s.cash,paid=s.choice==='send';
 const title=!paid?(s.choice==='hold'?'You kept space<br>to decide.':'You closed<br>the channel.'):s.recovery==='pay-recovery'?'Another fee.<br>No recovery.':'The loss stops<br>growing here.';
 const result=!paid?(s.choice==='hold'?'You set the offer aside and sent nothing. Your balance remains 100. Waiting did not verify the offer or create an obligation to act later.':'You declined and kept all 100 credits. You did not need the sender’s agreement to end contact.'):s.recovery==='pay-recovery'?'The recovery sender disappears too. You lost 40 on the first promise and 20 on the second. Your remaining balance is 40; none of the loss has been recovered.':`You end contact with 60 credits. The original 40 remain lost. ${s.recovery==='record'?'Your incident note exists only in the story; it is not a real report.':'Stopping prevented another payment in this story; it did not reverse the first one.'}`;
 return `<div class="eyebrow">THE DEBRIEF / WHAT THE EVIDENCE SUPPORTS</div><h1 id="scene-title" tabindex="-1">${title}</h1><p class="lead">${result}</p><div class="brief"><strong>${s.cash} remaining · ${loss} lost in this story</strong><span>Promised payments are not included in your balance. Nothing has been restored.</span></div><h2>What did you actually know?</h2><ul class="case-facts"><li><strong>The story's outcome:</strong> the original offer was an impersonation scam.${s.recovery==='pay-recovery'?' The recovery offer was another scam.':''} Real cases may remain uncertain.</li><li><strong>Your independent check:</strong> ${s.opened.includes('directory')?'you used the previously saved directory and learned Command had not authorized the offer.':'you did not use the saved directory. The copied seal, promise, and reviews could not verify the sender.'}</li><li><strong>Your right to decline:</strong> you could choose not to send credits even without proving who was behind the message.</li>${paid?'<li><strong>After a loss:</strong> another sender’s knowledge of the incident did not establish that it could recover money.</li>':''}</ul>${voice('The useful habit is not “distrust everything.” It is “know which source supports which claim.”')}<h2>Carry one distinction forward.</h2><p>A message includes a familiar seal, testimonials, and a contact button. Which step checks the claimed organization independently?</p><div class="choices">${option('quiz-sender','Ask through the message’s contact button','The same sender may control that channel too.')}${option('quiz-independent','Use contact details obtained separately','Reach the organization through a channel you already know, outside the message.')}</div><p id="feedback" class="feedback" role="status" aria-live="polite"></p><div id="completed" class="brief" hidden><strong>Chapter explored · Follow the source</strong><span id="saved"></span></div><div class="end-actions"><a href="after-the-crowd.html">Continue with Kael →</a><button data-action="restart">Replay another choice</button><a href="./">Return to the mission hub →</a></div>`;
}
function render(focus=true){
 $('scene').innerHTML=content();$('cash').textContent=state.cash;$('sent').textContent=100-state.cash;
 $('position').textContent=state.step==='intro'?'Message unopened':state.step==='reflect'?'Case debrief':state.choice==='send'?'Loss recorded / next decision pending':state.opened.includes('directory')?'Command denies authorization':'Sender remains unverified';
 $('notebook').replaceChildren();
 if(!state.opened.length){const li=document.createElement('li');li.textContent='No inquiries opened yet.';$('notebook').append(li);}
 for(const key of state.opened){const li=document.createElement('li'),title=document.createElement('strong'),kind=document.createElement('span');title.textContent=evidence[key].title;kind.textContent=evidence[key].kind;li.append(title,kind);$('notebook').append(li);}
 $('transactions').replaceChildren();for(const item of [{label:'Starting credits',delta:100},...state.history]){const li=document.createElement('li');li.textContent=`${item.label}: ${item.delta>0?'+':''}${item.delta}.`;$('transactions').append(li);}
 if(focus){const target=state.step==='investigate'&&state.active?$('finding-title'):$('scene-title');target.focus();target.scrollIntoView({block:'start'});}
}
$('scene').addEventListener('click',event=>{
 const button=event.target.closest('button[data-action]');if(!button)return;const action=button.dataset.action;
 if(action==='quiz-sender'){$('feedback').textContent='That asks the sender to verify itself. Try a channel obtained independently of this message.';return;}
 if(action==='quiz-independent'){
  $('feedback').textContent='Yes. An independently obtained contact route separates the organization from the sender’s claims.';
  let saved=false;try{globalThis.FederationPassport?.mark('borrowed-voice');sessionStorage.setItem('gf-journey-borrowed-voice-v1','complete');saved=true;}catch{}
  $('completed').hidden=false;$('saved').textContent=saved?'Your chapter marker is saved in this tab. No reward or rank is attached.':'You completed the reflection. This browser could not save a marker, but you can replay freely.';return;
 }
 state=action==='restart'?initialState():transition(state,action);render();
});
render(false);
