import {savings,savingsProjection} from './chapters-model.mjs';
import {startChapter,option,voice,heading,reflection} from './chapter-runtime.js?v=passport1';
startChapter({id:'changing-course',model:savings,
 metrics:s=>[['Saved now',s.saved],['Goal cost',s.target||'—'],['Weeks elapsed',s.elapsed]],
 status:s=>s.step==='reflect'?'Revised plan / future savings are a projection':'A plan in progress',
 notes:s=>['Starting goal savings: 30.',...(s.elapsed?[`Two actual deposits: ${s.oldRate} each.`]:[]),...(['goal-again','break','revise','reflect'].includes(s.step)?['Essential repair paid: 20.']:[]),...(s.step==='reflect'?[`Planned contribution break: ${s.breakWeeks} weeks.`,`Planned rate afterward: ${s.rate} per week. No future deposits have occurred.`]:[])],
 wrong:'An old deadline does not account for changed costs or available savings. It can be revised without abandoning the goal.',
 right:'Yes. Start with the money actually available, then revise the goal, pace, or date to fit the new situation.',
 content(s){
  if(s.step==='intro')return heading('AELA / A DEEPER MISSION · ABOUT 6–9 MINUTES','Changing<br><em>course.</em>','You made a plan for something that matters. Then life changed. How do you make the plan useful again?')+'<div class="panorama"><img src="assets/first-contact.png" alt="Aela and the four other Federation guides."></div>'+voice('Aela','A plan is a way to care for a future you. It can also make room for the person you are today.')+'<p>You have 30 credits saved for an observatory visit. Choose your goal and weekly pace. After two weeks, an essential repair interrupts the plan. Your task is to revise it, not to pretend the interruption never happened.</p><button class="primary" data-action="begin">Make room for the goal →</button>';
  if(s.step==='goal')return heading('01 / NAME WHAT MATTERS','What would<br>you like to do?','Both visits are optional experiences. Regular essentials are covered in the starting scenario.')+`<div class="choices">${option('90','A full-day visit · 90 credits','A quiet day of guided stargazing.')}${option('120','A shared visit · 120 credits','Bring a friend for the full-day experience.')}</div>`+voice('Aela','There is no more worthy answer. Choose the experience that matters to you in this story.');
  if(s.step==='pace')return heading('02 / A STARTING PACE','What can<br>the plan hold?','Choose a fictional weekly contribution. It is added at the end of each week, after regular essentials.')+`<div class="choices">${[5,10,15].map(n=>option(String(n),`${n} credits each week`,`After two weeks, your saved balance will be ${30+2*n}.`)).join('')}</div><p class="fine">The available choices are invented, not an assessment of anyone's ability to save. No interest, fees, or price changes are modeled.</p>`;
  if(s.step==='change')return heading('03 / SOMETHING ELSE NEEDS YOU','A broken<br>home air filter.',`Two weeks passed. You added ${s.oldRate} twice and now have ${s.saved} saved. An essential replacement filter costs 20.`)+voice('Aela','The filter matters now. Using money for something essential is not a failure of the person who saved it.')+`<p>This exercise has no separate repair fund and assumes no refund, borrowing, assistance, or other income. The filter must be replaced. Paying for it leaves ${s.saved-20} toward your visit.</p><button class="primary" data-action="cover">Pay 20 for the filter →</button><p class="fine">Real situations may offer other options. The story limits them so we can explore updating a plan after an expense.</p>`;
  if(s.step==='goal-again')return heading('04 / KEEP THE PURPOSE, REVISIT THE SHAPE','Does the same<br>goal still fit?',`You have ${s.saved} saved. Your original visit costs ${s.originalTarget}. A shorter solo twilight visit costs 60.`)+`<div class="choices">${option('keep',`Keep the original visit · ${s.originalTarget}`,`Still need ${s.originalTarget-s.saved}. Accept a later date if needed.`)}${option('smaller','Choose the twilight visit · 60',`Still need ${60-s.saved}. A different experience at a lower cost; no money is spent by choosing it.`)}</div>`+voice('Aela','You can keep the dream, change its shape, or change its timing. The choice belongs to you.');
  if(s.step==='break')return heading('05 / ROOM FOR TODAY','A break can<br>be part of a plan.','The crew has had a demanding week. Decide whether to schedule a short contribution break before restarting.')+`<div class="choices">${option('continue','Resume without a planned break','No extra pause weeks. Choose a realistic rate next.')}${option('pause','Take a two-week contribution break',`Keep the ${s.saved} already saved. Add nothing during the break. Shift a possible arrival date two weeks later.`)}</div><p class="fine">Regular essentials remain covered. A break does not spend or erase the existing savings in this scenario.</p>`;
  if(s.step==='revise')return heading('06 / CHOOSE A SUSTAINABLE ASSUMPTION','What happens<br>from here?',`Goal: ${s.target}. Saved now: ${s.saved}. Planned break: ${s.breakWeeks} weeks. Choose your contribution rate after that break.`)+`<div class="choices">${[0,5,10,15].map(n=>option(String(n),n===0?'Pause contributions for now':`${n} credits per week`,n===0?'Keep current savings. No arrival date can be projected until the plan changes.':'A forecast assuming that amount is added at each week’s end.')).join('')}</div>`;
  const p=savingsProjection(s);
  return heading('THE DEBRIEF / A PLAN THAT CAN CHANGE','The goal is<br>still yours.',p.weeks===null?`You still have ${s.saved} saved. With no further contributions, this plan has no projected arrival date.`:`You still have ${s.saved} saved. After the ${s.breakWeeks}-week break, ${p.weeks} weeks of contributions at ${s.rate} would reach the ${s.target}-credit goal.`)+`<div class="brief"><strong>${p.arrivalWeek===null?'Date open':`Projected arrival: end of week ${p.arrivalWeek}`}</strong><span>Two weeks have actually elapsed. ${p.arrivalWeek===null?'No future deposits are assumed at the selected zero rate.':`${s.breakWeeks} break weeks + ${p.weeks} contribution weeks are still future assumptions.`} The visit has not been paid for or reached.</span></div><p><strong>Current balance:</strong> 30 + ${s.oldRate} + ${s.oldRate} − 20 = ${s.saved}.</p><h2>Change the pace, see the date.</h2><p>Same revised goal and break. No fees, interest, withdrawals, or price changes.</p><div class="table-scroll" tabindex="0" role="region" aria-label="Contribution forecast"><table><thead><tr><th>Weekly amount</th><th>Contribution weeks needed</th><th>Arrival week</th></tr></thead><tbody>${[0,5,10,15].map(rate=>{const x=savingsProjection(s,rate);return `<tr${rate===s.rate?' class="selected"':''}><th scope="row">${rate}${rate===s.rate?' · chosen':''}</th><td>${x.weeks??'No date'}</td><td>${x.arrivalWeek??'Open'}</td></tr>`;}).join('')}</tbody></table></div>`+voice('Aela','A later date can be an honest plan. A faster date is useful only if its assumptions fit your life.')+reflection('An essential expense changes your savings. What makes the next plan useful?','Keep the old date even if the numbers no longer fit.','Update the balance, goal, contributions, and timing.');
 }
});
