
'use strict';
const $=id=>document.getElementById(id),screens=['intro','goal','choice','result'];let target=60,spending=0;
function show(id){screens.forEach(s=>$(s).hidden=s!==id);document.querySelectorAll('.progress span').forEach((s,i)=>s.classList.toggle('on',i<=screens.indexOf(id)));$(id).querySelector('h1,h2').focus();window.scrollTo(0,0)}
function clearQuiz(){$('feedback').textContent='';$('complete').hidden=true}
function goal(n){target=n;$('goalSummary').textContent='Your '+(n===60?'solo':'shared')+' visit costs '+n+' credits. You have 30 saved.';clearQuiz();show('choice')}
function forecast(){const weekly=Number($('weekly').value),remaining=target-(30-spending);$('weeklyValue').textContent=weekly;$('forecast').textContent=weekly===0?'With no new savings, the balance stays at '+(30-spending)+' credits. There is no arrival date under this assumption.':'At '+weekly+' credits saved at each week’s end, you reach the goal after '+Math.ceil(remaining/weekly)+' weeks. This assumes you keep adding that amount and make no further withdrawals.'}
function choose(n){spending=n;const saved=30-n,remaining=target-saved,weeks=Math.ceil(remaining/10),baseline=Math.ceil((target-30)/10);$('headline').textContent=n===0?'Your journey stays on its earlier timeline.':'You chose an experience today and a later journey.';$('summary').textContent='Festival spending: '+n+' credits. Goal savings remaining: '+saved+' credits. Your target is '+target+'.';$('timeline').textContent=weeks+' weeks to your goal';$('math').textContent=target+' target − '+saved+' already saved = '+remaining+' still needed. At 10 per week, that takes '+weeks+' weeks.';$('tradeoff').textContent=n===0?'The free parade adds no delay to this savings plan.':'Compared with spending nothing tonight, this choice adds '+(weeks-baseline)+' '+(weeks-baseline===1?'week':'weeks')+'. You decide whether the festival experience is worth that time.';$('weekly').value=10;forecast();clearQuiz();show('result')}
$('start').onclick=()=>{clearQuiz();show('goal')};document.querySelectorAll('[data-goal]').forEach(b=>b.onclick=()=>goal(Number(b.dataset.goal)));document.querySelectorAll('[data-spend]').forEach(b=>b.onclick=()=>choose(Number(b.dataset.spend)));$('weekly').oninput=forecast;$('quizBad').onclick=()=>{$('feedback').textContent='A spending choice can change the timing without ending the goal. You can make a new plan.';$('complete').hidden=true};$('quizGood').onclick=()=>{$('feedback').textContent='Yes. A useful plan shows the tradeoffs and can change with your priorities and circumstances.';$('complete').hidden=false};$('retry').onclick=()=>goal(target);$('newGoal').onclick=()=>{clearQuiz();show('goal')};$('home').onclick=()=>{clearQuiz();show('intro')};
