
'use strict';
const $=id=>document.getElementById(id),screens=['intro','plan','result','lab'];
const plans={small:{name:'Small stall',fee:20,price:10,sold:8},large:{name:'Central stall',fee:60,price:10,sold:12},sale:{name:'Central stall with a sale',fee:60,price:6,sold:20}};let selected='small';
function numbers(p,n){const revenue=p.price*n,cost=4*n+p.fee,profit=revenue-cost;return {revenue,cost,profit,balance:200+profit}}
function show(id){screens.forEach(s=>$(s).hidden=s!==id);document.querySelectorAll('.progress span').forEach((s,i)=>s.classList.toggle('on',i<=screens.indexOf(id)));$(id).querySelector('h1,h2').focus();window.scrollTo(0,0)}
function reset(id){$('feedback').textContent='';$('complete').hidden=true;show(id)}
function choose(key){selected=key;const p=plans[key],v=numbers(p,p.sold);$('headline').textContent=v.profit>=0?'You kept '+v.profit+' credits after the costs.':'More customers. A '+(-v.profit)+'-credit loss.';$('story').textContent=p.name+': '+p.sold+' travelers each buy a charm for '+p.price+' credits.';$('revenue').textContent=v.revenue+' credits';$('making').textContent=(4*p.sold)+' credits';$('fee').textContent=p.fee+' credits';$('profitLabel').textContent=v.profit<0?'Loss':'Profit';$('profit').textContent=Math.abs(v.profit)+' credits';$('balance').textContent=v.balance+' credits';$('explanation').textContent='Revenue is the money from sales. Subtract the costs in this model to find the profit or loss: '+v.revenue+' − '+v.cost+' = '+v.profit+'. Your original 200 credits are starting funds, not sales revenue.';$('comparison').innerHTML=Object.entries(plans).map(([k,q])=>{const w=numbers(q,q.sold);return '<tr><th scope="row">'+q.name+(k===key?' · your plan':'')+'</th><td>'+q.sold+'</td><td>'+w.revenue+'</td><td>'+w.cost+'</td><td>'+w.profit+'</td></tr>'}).join('');show('result')}
function update(){const p=plans[selected],n=Number($('customers').value),v=numbers(p,n);$('sold').textContent=n;$('labResult').textContent='Revenue '+v.revenue+' − costs '+v.cost+' = '+(v.profit<0?'loss '+(-v.profit):'profit '+v.profit)+' credits. Ending balance: '+v.balance+'.';$('breakEven').textContent='Each sale leaves '+(p.price-4)+' credits after materials. You need '+Math.ceil(p.fee/(p.price-4))+' sales to cover the '+p.fee+'-credit stall fee and break even in this model.'}
$('start').onclick=()=>reset('plan');document.querySelectorAll('[data-plan]').forEach(b=>b.onclick=()=>choose(b.dataset.plan));$('explore').onclick=()=>{const p=plans[selected];$('labPlan').textContent=p.name+' · price '+p.price+' · materials 4 per charm · stall fee '+p.fee+'. Move the slider to explore possible sales, not a prediction.';$('customers').value=p.sold;update();show('lab')};$('customers').oninput=update;$('quizRevenue').onclick=()=>{$('feedback').textContent='120 is the revenue. After paying 140 in costs, the stall has 20 less than it started with. Try again.';$('complete').hidden=true};$('quizLoss').onclick=()=>{$('feedback').textContent='Exactly. 120 − 140 = −20. Strong sales can still leave a loss.';$('complete').hidden=false};$('replay').onclick=()=>reset('plan');$('home').onclick=()=>reset('intro');
