import {boards,jobs,initial,reason,step,result} from './supply-run-model.mjs';
const $=id=>document.getElementById(id);let state=initial(),last=null;
function render(){const b=boards[state.board],r=result(state);$('cash').textContent=state.cash;$('fuel').textContent=state.fuel;$('time').textContent=state.time;$('target').textContent=b.target;$('run-name').textContent=b.name;$('briefing').textContent=b.note;
 $('route-count').textContent=state.done.length+' of 3 delivery slots used';$('dock').disabled=state.ended;$('dock').textContent=state.done.length===3?'Return to port and see your result →':'Return to port now →';
 const list=jobs(state.board);let points='230,160';for(const id of state.done){const j=list.find(j=>j.id===id);points+=' '+j.x+','+j.y;}if(state.ended)points+=' 230,160';
 $('chart').innerHTML=`<svg viewBox="0 0 480 320" role="img" aria-label="Delivery route. ${state.done.length} stops completed${state.ended?', returned to port':''}."><defs><radialGradient id="orbit"><stop stop-color="#254e60"/><stop offset="1" stop-color="#0b1728"/></radialGradient></defs><rect width="480" height="320" rx="24" fill="url(#orbit)"/><circle cx="230" cy="160" r="110" fill="none" stroke="#3e6273" stroke-dasharray="3 7"/><polyline points="${points}" fill="none" stroke="#efd083" stroke-width="3"/><circle cx="230" cy="160" r="13" fill="#efd083"/><text x="230" y="192" text-anchor="middle">PORT</text>${list.map(j=>`<circle cx="${j.x}" cy="${j.y}" r="${state.done.includes(j.id)?10:6}" fill="${state.done.includes(j.id)?'#efd083':'#85deeb'}"/><text x="${j.x}" y="${j.y+25}" text-anchor="middle">${j.place}</text>`).join('')}</svg>`;
 $('deliveries').innerHTML=list.map(j=>{const why=reason(state,j.id);return `<article class="delivery ${state.done.includes(j.id)?'delivered':''}"><div class="eyebrow">${j.place}</div><h3>${j.name}</h3><dl><div><dt>Pay upfront</dt><dd>${j.cost}</dd></div><div><dt>Receive on arrival</dt><dd>${j.pay}</dd></div><div><dt>Net gain</dt><dd>+${j.pay-j.cost}</dd></div><div><dt>Fuel / time</dt><dd>${j.fuel} / ${j.time}</dd></div></dl><button data-job="${j.id}" ${why?'disabled':''}>${state.done.includes(j.id)?'Delivered ✓':'Deliver '+j.name}</button>${why?`<p class="reason">${why}</p>`:''}</article>`}).join('');
 $('ledger-lines').replaceChildren();for(const e of state.ledger){const li=document.createElement('li');li.textContent=list.find(j=>j.id===e.id).name+': −'+e.cost+' cost, +'+e.pay+' payment = +'+e.net+' net';$('ledger-lines').append(li);}
 $('result').hidden=!state.ended;if(state.ended){$('result-title').textContent=r.met?'Route complete. Goal reached!':'Home safely. A different route could do more.';$('result-copy').textContent=`You returned with ${state.cash} credits: ${b.cash} starting credits plus ${r.gain} net earnings. Your target was ${b.target}. You used ${state.done.length} ${state.done.length===1?"delivery":"deliveries"} and kept ${state.fuel} fuel and ${state.time} time after returning.`;}
 $('last-run').textContent=last?`Previous ${boards[last.board].name} run: ${last.cash} credits, ${last.done.length} ${last.done.length===1?"delivery":"deliveries"}. Compare results within the same scenario; starting resources differ.`:'Your next completed run can be compared here. Run comparisons last while this page stays open.';
}
$('deliveries').addEventListener('click',event=>{const button=event.target.closest('button[data-job]');if(!button||button.disabled)return;const id=button.dataset.job;state=step(state,id);render();$('run-message').textContent=jobs(state.board).find(j=>j.id===id).name+` delivered. ${state.cash} credits, ${state.fuel} fuel and ${state.time} time remain.`;$('run-message').focus();});
$('dock').addEventListener('click',()=>{state=step(state,'dock');render();$('result-title').focus();$('result').scrollIntoView({block:'center'});});
$('new-run').addEventListener('click',()=>{if(state.ended)last=state;state=initial($('scenario').value);render();$('run-message').textContent='New '+boards[state.board].name+' run ready. All delivery costs are shown below.';$('run-message').focus();});render();
