import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
const code=['avatar-model.js','avatar-mission.js'].map(f=>readFileSync(new URL('../journey/'+f,import.meta.url),'utf8')).join('\n');
function boot(raw=null,blocked=false){const nodes=new Map(),events={};let value=raw;const get=id=>{if(!nodes.has(id))nodes.set(id,{hidden:false,innerHTML:'',textContent:'',append(img){this.image=img;}});return nodes.get(id);};vm.runInNewContext(code,{document:{getElementById:get,createElement(){return {addEventListener(k,f){this[k]=f;}};}},localStorage:{getItem(){if(blocked)throw Error();return value;}},window:{addEventListener(k,f){events[k]=f;}}});return {get,events,update(v){value=v;},nodes};}
test('missing blocked and malformed identity never blocks mission',()=>{for(const t of [boot(),boot(null,true),boot('{'),boot('[]')])assert.equal(t.get('mission-avatar').hidden,true);});
test('identity updates and removal touch only presentation nodes',()=>{const t=boot(JSON.stringify({callsign:'<script>x</script>'}));assert.equal(t.get('mission-avatar-name').textContent,'<script>x</script>');assert.ok(!t.get('mission-avatar-portrait').innerHTML.includes('<script>'));t.update(JSON.stringify({callsign:'Nova'}));t.events.storage({key:'gf-journey-avatar-v1'});assert.equal(t.get('mission-avatar-name').textContent,'Nova');t.update(null);t.events.pageshow();assert.equal(t.get('mission-avatar').hidden,true);assert.deepEqual([...t.nodes.keys()].sort(),['mission-avatar','mission-avatar-name','mission-avatar-portrait']);});
test('bad photos preserve callsign without a remote image',()=>{const t=boot(JSON.stringify({mode:'photo',photo:'https://example.com/a',callsign:'Nova'}));assert.equal(t.get('mission-avatar').hidden,false);assert.equal(t.get('mission-avatar-portrait').hidden,true);const a=boot(JSON.stringify({mode:'photo',photo:'data:image/jpeg;base64,YQ=='}));a.get('mission-avatar-portrait').image.error();assert.equal(a.get('mission-avatar-portrait').hidden,true);});
test('all eleven missions load shared identity and edit in separate tab',()=>{for(const name of ['repair-the-shuttle','the-signal','starport-market','observatory-journey','docking-request','long-way-home','borrowed-voice','after-the-crowd','changing-course','keys-to-the-gate','meridian-relay']){const html=readFileSync(new URL('../journey/'+name+'.html',import.meta.url),'utf8');assert.equal((html.match(/id="mission-avatar"/g)||[]).length,1);assert.ok(html.indexOf('src="avatar-model.js"')<html.indexOf('src="avatar-mission.js"'));assert.match(html,/href="avatar.html" target="_blank" rel="noopener noreferrer"/);}});
