import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
const code=['avatar-model.js','avatar-hub.js'].map(f=>readFileSync(new URL('../journey/'+f,import.meta.url),'utf8')).join('\n');
function boot(raw=null,blocked=false){const nodes=new Map(),events={};let value=raw;const get=id=>{if(!nodes.has(id))nodes.set(id,{textContent:'',innerHTML:'',hidden:false,append(img){this.image=img;}});return nodes.get(id);};vm.runInNewContext(code,{document:{getElementById:get,createElement(){return {addEventListener(k,f){this[k]=f;}};}},localStorage:{getItem(){if(blocked)throw Error();return value;}},window:{addEventListener(k,f){events[k]=f;}}});return {get,events,update(v){value=v;}};}
test('no saved avatar or invalid storage leaves invitation and missions available',()=>{for(const t of [boot(),boot('{'),boot('null'),boot('[]'),boot(null,true)]){assert.equal(t.get('saved-avatar-portrait').hidden,true);assert.equal(t.get('avatar-link').textContent,'Create your avatar →');}});
test('character matches shared renderer and callsign remains plain text',()=>{const t=boot(JSON.stringify({callsign:'<img src=x>',form:'luminary',accent:'gold'}));assert.equal(t.get('avatarTitle').textContent,'Welcome aboard, <img src=x>.');assert.ok(t.get('saved-avatar-portrait').innerHTML.includes('#efd083'));assert.ok(!t.get('saved-avatar-portrait').innerHTML.includes('<img'));assert.equal(t.get('avatar-link').textContent,'Edit your avatar →');});
test('photo uses only validated local image; failed decode has recovery message',()=>{const t=boot(JSON.stringify({mode:'photo',photo:'data:image/jpeg;base64,YQ=='}));assert.equal(t.get('saved-avatar-portrait').image.src,'data:image/jpeg;base64,YQ==');t.get('saved-avatar-portrait').image.error();assert.equal(t.get('saved-avatar-portrait').hidden,true);assert.match(t.get('saved-avatar-note').textContent,/could not be displayed/);const bad=boot(JSON.stringify({mode:'photo',photo:'https://example.com/a.jpg'}));assert.equal(bad.get('saved-avatar-portrait').hidden,true);});
test('return navigation and storage events refresh saved and removed avatars',()=>{const t=boot();t.update(JSON.stringify({callsign:'Nova'}));t.events.pageshow();assert.equal(t.get('avatarTitle').textContent,'Welcome aboard, Nova.');t.update(null);t.events.storage({key:'unrelated'});assert.equal(t.get('avatar-link').textContent,'Edit your avatar →');t.events.storage({key:'gf-journey-avatar-v1'});assert.equal(t.get('avatar-link').textContent,'Create your avatar →');assert.equal(t.get('saved-avatar-portrait').hidden,true);});
