const {test}=require('node:test');const assert=require('node:assert/strict');const {readFileSync}=require('node:fs');const {runInNewContext}=require('node:vm');const source=readFileSync(require('node:path').join(__dirname,'../assets/federation/fed-deck-phantom.js'),'utf8');const mint='Dc9CeuctqvP947ipnCJb8fSf6HhNWDooAQxsVHj2RNBV';
function setup(provider){const nodes=new Map();let submits=0;const document={getElementById(id){if(!nodes.has(id))nodes.set(id,{value:'',textContent:'',hidden:false,disabled:false,events:{},addEventListener(k,f){(this.events[k]??=[]).push(f);},dispatchEvent(e){for(const f of this.events[e.type]||[])f(e);},requestSubmit(){submits++;}});return nodes.get(id);}};runInNewContext(source,{document,Event,globalThis:{phantom:provider?{solana:provider}:undefined}});return {nodes,submits:()=>submits,click:id=>nodes.get(id).events.click[0]()};}
function provider(){const events={};let connects=0,disconnects=0;return {isPhantom:true,events,on(k,f){events[k]=f;},connect:async()=>{connects++;return {publicKey:{toString:()=>mint}};},disconnect:async()=>{disconnects++;},signMessage(){throw Error('must never sign');},signTransaction(){throw Error('must never transact');},counts:()=>({connects,disconnects})};}
test('no eager connection; explicit action loads an address and submits only the balance form',async()=>{const p=provider();const app=setup(p);assert.equal(p.counts().connects,0);await app.click('phantom-connect');assert.equal(p.counts().connects,1);assert.equal(app.nodes.get('wallet-address').value,mint);assert.equal(app.submits(),1);assert.equal(app.nodes.get('phantom-disconnect').hidden,false);});
test('missing Phantom and user rejection preserve the address-entry fallback',async()=>{const app=setup();await app.click('phantom-connect');assert.match(app.nodes.get('phantom-message').textContent,/not detected/);assert.equal(app.submits(),0);const p=provider();p.connect=async()=>{throw {code:4001,message:'do not expose raw wallet detail'};};const denied=setup(p);await denied.click('phantom-connect');assert.match(denied.nodes.get('phantom-message').textContent,/cancelled/);assert.equal(denied.submits(),0);});
test('Clear during a wallet permission request suppresses a late address and disconnects',async()=>{const p=provider();let resolve;p.connect=()=>new Promise(r=>resolve=r);const app=setup(p);const pending=app.click('phantom-connect');await app.click('wallet-clear');resolve({publicKey:{toString:()=>mint}});await pending;assert.equal(app.submits(),0);assert.equal(app.nodes.get('wallet-address').value,'');assert.equal(p.counts().disconnects,1);});
test('account change clears old display through input event without automatically reading a new wallet',async()=>{const p=provider();const app=setup(p);await app.click('phantom-connect');let changes=0;app.nodes.get('wallet-address').addEventListener('input',()=>changes++);p.events.accountChanged({toString:()=> '11111111111111111111111111111111'});assert.equal(changes,1);assert.equal(app.submits(),1);assert.match(app.nodes.get('phantom-message').textContent,/Press Read/);});
test('disconnect clears the Phantom-sourced address while retaining manually entered watch addresses',async()=>{const p=provider();const app=setup(p);await app.click('phantom-connect');await app.click('phantom-disconnect');assert.equal(app.nodes.get('wallet-address').value,'');const p2=provider();const watched=setup(p2);await watched.click('phantom-connect');watched.nodes.get('wallet-address').value='11111111111111111111111111111111';await watched.click('phantom-disconnect');assert.equal(watched.nodes.get('wallet-address').value,'11111111111111111111111111111111');});
test('late account events after disconnect cannot restore the address',async()=>{const p=provider();const app=setup(p);await app.click('phantom-connect');await app.click('phantom-disconnect');p.events.accountChanged({toString:()=>mint});assert.equal(app.nodes.get('wallet-address').value,'');assert.equal(app.submits(),1);});
test('account events before address approval cannot load an address',async()=>{const p=provider();let resolve;p.connect=()=>new Promise(r=>resolve=r);const app=setup(p);const pending=app.click('phantom-connect');p.events.accountChanged({toString:()=>mint});assert.equal(app.nodes.get('wallet-address').value,'');resolve({publicKey:{toString:()=>mint}});await pending;assert.equal(app.nodes.get('wallet-address').value,mint);assert.equal(app.submits(),1);});
test('failed disconnect clears the source and ignores later account events while allowing retry',async()=>{const p=provider();const app=setup(p);await app.click('phantom-connect');p.disconnect=async()=>{throw Error('private provider detail');};await app.click('phantom-disconnect');assert.equal(app.nodes.get('wallet-address').value,'');p.events.accountChanged({toString:()=>mint});assert.equal(app.nodes.get('wallet-address').value,'');assert.match(app.nodes.get('phantom-message').textContent,/could not be confirmed/);assert.ok(!app.nodes.get('phantom-message').textContent.includes('private provider detail'));assert.equal(app.nodes.get('phantom-disconnect').hidden,false);p.disconnect=async()=>{};await app.click('phantom-disconnect');assert.equal(app.nodes.get('phantom-disconnect').hidden,true);});
test('Clear prevents a late connection rejection from overwriting the clear status',async()=>{const p=provider();let reject;p.connect=()=>new Promise((_,r)=>reject=r);const app=setup(p);const pending=app.click('phantom-connect');await app.click('wallet-clear');reject({code:4001});await pending;assert.match(app.nodes.get('phantom-message').textContent,/cleared/);});
