const {test}=require('node:test');const assert=require('node:assert/strict');const {readFileSync}=require('node:fs');const {runInNewContext}=require('node:vm');
const source=readFileSync(require('node:path').join(__dirname,'../assets/federation/fed-deck.js'),'utf8');
function setup(fetch,passport,timers={setTimeout,clearTimeout}){const nodes=new Map();function node(){return {textContent:'',value:'',disabled:false,children:[],events:{},attributes:{},setAttribute(k,v){this.attributes[k]=v;},addEventListener(k,f){this.events[k]=f;},append(c){this.children.push(c);if(!this.firstChild)this.firstChild=c;},replaceChildren(){this.children=[];}};}const document={getElementById(id){if(!nodes.has(id))nodes.set(id,node());return nodes.get(id);},createElement:node,createElementNS:node};runInNewContext(source,{document,fetch,AbortController,Date,setTimeout:timers.setTimeout,clearTimeout:timers.clearTimeout,globalThis:{FederationPassport:passport}});return {nodes,submit:()=>nodes.get('wallet-form').events.submit({preventDefault(){}}),clear:()=>nodes.get('wallet-clear').events.click()};}
test('invalid input never sends a lookup',async()=>{let calls=0;const app=setup(async()=>{calls++;});app.nodes.get('wallet-address').value='seed phrase is never a wallet address';await app.submit();assert.equal(calls,0);assert.equal(app.nodes.get('wallet-rows').children.length,0);});
test('lookup omits credentials and clear prevents a late response restoring balances',async()=>{let resolve;const app=setup((url,options)=>{assert.equal(url,'/api/federation-wallet');assert.equal(options.credentials,'omit');return new Promise(r=>resolve=r);});app.nodes.get('wallet-address').value='11111111111111111111111111111111';const pending=app.submit();app.clear();resolve({ok:true,status:200,json:async()=>({address:'11111111111111111111111111111111',sol:'1',tokens:[],tokenAccounts:0,observedAt:new Date().toISOString()})});await pending;assert.equal(app.nodes.get('wallet-rows').children.length,0);assert.equal(app.nodes.get('wallet-address').value,'');assert.equal(app.nodes.get('wallet-state').textContent,'No address loaded');});
test('upstream failures clear previous data and cannot masquerade as zero',async()=>{const app=setup(async()=>({ok:false,status:503,json:async()=>({error:'Service unavailable'})}));app.nodes.get('wallet-address').value='11111111111111111111111111111111';app.nodes.get('wallet-rows').children=[{}];await app.submit();assert.equal(app.nodes.get('wallet-rows').children.length,0);assert.equal(app.nodes.get('wallet-message').textContent,'Service unavailable');assert.equal(app.nodes.get('wallet-count').textContent,'—');});
test('priced allocation excludes unpriced tokens but retains their quantities',async()=>{const address='11111111111111111111111111111111';const app=setup(async()=>({ok:true,status:200,json:async()=>({address,sol:'2',tokens:[{mint:'unpriced-mint',symbol:'GFOF',quantity:'500'}],tokenAccounts:1,observedAt:new Date().toISOString(),pricing:{status:'available',prices:{So11111111111111111111111111111111111111112:{usdPrice:100,blockId:123}}}})}));app.nodes.get('wallet-address').value=address;await app.submit();assert.equal(app.nodes.get('priced-total').textContent,'$200.00');assert.match(app.nodes.get('price-coverage').textContent,/1 assets priced; 1 nonzero assets excluded/);assert.equal(app.nodes.get('wallet-rows').children.length,2);assert.equal(app.nodes.get('wallet-rows').children[1].children[1].textContent,'500');assert.equal(app.nodes.get('holdings-graph').children.length,1);assert.equal(app.nodes.get('holdings-graph').children[0].children[1].value,1);});

test('mission panel reads optional passport without writing or making network requests',()=>{let done=['repair-the-shuttle','repair-the-shuttle','unknown'];const passport={missions:[['repair-the-shuttle','Repair the Shuttle','Sera','Prepared explorer'],['the-signal','The Signal','Oryn','Signal seeker']],read:()=>({enabled:true,available:true,done}),write:()=>{throw Error('must not write');}};const app=setup(()=>{throw Error('must not fetch');},passport);assert.equal(app.nodes.get('explorer-rank').textContent,'1 / 2');assert.equal(app.nodes.get('mission-progress').value,1);assert.equal(app.nodes.get('next-mission').href,'/journey/the-signal.html');assert.equal(app.nodes.get('mission-collection').children.length,2);done.push('the-signal');app.nodes.get('mission-refresh').events.click();assert.equal(app.nodes.get('explorer-rank').textContent,'2 / 2');});
test('unavailable passport storage is shown as unknown instead of completed or empty',()=>{const passport={missions:[['repair-the-shuttle','Repair','Sera','Prepared explorer']],read:()=>({enabled:false,available:false,done:[]})};const app=setup(()=>{throw Error('must not fetch');},passport);assert.equal(app.nodes.get('explorer-rank').textContent,'Progress unavailable');assert.match(app.nodes.get('mission-message').textContent,/storage is unavailable/);assert.equal(app.nodes.get('mission-collection').children[0].children[0].textContent,'STATUS UNAVAILABLE');});

test('history uses actual same-address observations and Clear removes them',async()=>{let count=0;const address='11111111111111111111111111111111';const app=setup(async()=>({ok:true,status:200,json:async()=>({address,sol:String(++count),tokens:[],tokenAccounts:0,observedAt:new Date(1700000000000+count*1000).toISOString()})}));app.nodes.get('wallet-address').value=address;await app.submit();await app.submit();assert.equal(app.nodes.get('balance-history-rows').children.length,2);assert.equal(app.nodes.get('balance-history-plot').children.length,1);assert.match(app.nodes.get('balance-history-message').textContent,/not investment profit/);app.clear();assert.equal(app.nodes.get('balance-history-rows').children.length,0);});
test('history does not mix addresses or preserve readings after a failed lookup',async()=>{let fail=false;const app=setup(async(url,o)=>({ok:!fail,status:fail?503:200,json:async()=>fail?{error:'Unavailable'}:{address:JSON.parse(o.body).address,sol:'1',tokens:[],tokenAccounts:0,observedAt:new Date().toISOString()}}));app.nodes.get('wallet-address').value='11111111111111111111111111111111';await app.submit();app.nodes.get('wallet-address').value='Dc9CeuctqvP947ipnCJb8fSf6HhNWDooAQxsVHj2RNBV';await app.submit();assert.equal(app.nodes.get('balance-history-rows').children.length,1);fail=true;await app.submit();assert.equal(app.nodes.get('balance-history-rows').children.length,0);});

test('Clear during response decoding cannot restore stale balances or history',async()=>{let decode;const address='11111111111111111111111111111111';const app=setup(async()=>({ok:true,status:200,json:()=>new Promise(resolve=>decode=resolve)}));app.nodes.get('wallet-address').value=address;const pending=app.submit();await new Promise(setImmediate);app.clear();decode({address,sol:'1',tokens:[],tokenAccounts:0,observedAt:new Date().toISOString()});await pending;assert.equal(app.nodes.get('wallet-rows').children.length,0);assert.equal(app.nodes.get('balance-history-rows').children.length,0);assert.equal(app.nodes.get('wallet-state').textContent,'No address loaded');});
test('editing an address cancels in-flight decoding and clears the previous address display',async()=>{let decode;const address='11111111111111111111111111111111';const app=setup(async()=>({ok:true,status:200,json:()=>new Promise(resolve=>decode=resolve)}));app.nodes.get('wallet-address').value=address;const pending=app.submit();await new Promise(setImmediate);app.nodes.get('wallet-address').value='Dc9CeuctqvP947ipnCJb8fSf6HhNWDooAQxsVHj2RNBV';app.nodes.get('wallet-address').events.input();decode({address,sol:'1',tokens:[],tokenAccounts:0,observedAt:new Date().toISOString()});await pending;assert.equal(app.nodes.get('wallet-rows').children.length,0);assert.equal(app.nodes.get('wallet-load').disabled,false);});

test('a stuck lookup reaches the deadline and releases the button',async()=>{let expire,cleared=0;const app=setup((url,o)=>new Promise((resolve,reject)=>o.signal.addEventListener('abort',()=>reject(Object.assign(Error('abort'),{name:'AbortError'})))),undefined,{setTimeout(callback,delay){assert.equal(delay,20000);expire=callback;return 1;},clearTimeout(){cleared++;}});app.nodes.get('wallet-address').value='11111111111111111111111111111111';const pending=app.submit();expire();await pending;assert.match(app.nodes.get('wallet-message').textContent,/timed out/);assert.equal(app.nodes.get('wallet-load').disabled,false);assert.equal(cleared,1);assert.equal(app.nodes.get('wallet-rows').children.length,0);});

test('price coverage uses nonzero asset count rather than quantities and resets on Clear',async()=>{const address='11111111111111111111111111111111';const app=setup(async()=>({ok:true,status:200,json:async()=>({address,sol:'2',tokens:[{mint:'unpriced',quantity:'999999999'}],tokenAccounts:1,observedAt:new Date().toISOString(),pricing:{prices:{So11111111111111111111111111111111111111112:{usdPrice:100}}}})}));app.nodes.get('wallet-address').value=address;await app.submit();assert.equal(app.nodes.get('wallet-price-status').textContent,'PARTIAL PRICE COVERAGE');assert.equal(app.nodes.get('wallet-priced-count').textContent,'1');assert.equal(app.nodes.get('wallet-unpriced-count').textContent,'1');assert.equal(app.nodes.get('wallet-coverage-meter').max,2);assert.equal(app.nodes.get('wallet-coverage-meter').value,1);assert.match(app.nodes.get('wallet-coverage-label').textContent,/by asset count/);app.clear();assert.equal(app.nodes.get('wallet-priced-count').textContent,'—');assert.equal(app.nodes.get('wallet-unpriced-count').textContent,'—');assert.equal(app.nodes.get('wallet-coverage-meter').hidden,true);});
test('zero balances and a price outage have distinct coverage states without claiming completeness',async()=>{const address='11111111111111111111111111111111';let sol='0';const app=setup(async()=>({ok:true,status:200,json:async()=>({address,sol,tokens:[],tokenAccounts:0,observedAt:new Date().toISOString(),pricing:{status:'unavailable',prices:{}}})}));app.nodes.get('wallet-address').value=address;await app.submit();assert.equal(app.nodes.get('wallet-price-status').textContent,'NO NONZERO HOLDINGS');assert.equal(app.nodes.get('wallet-coverage-meter').hidden,true);sol='1';await app.submit();assert.equal(app.nodes.get('wallet-price-status').textContent,'PRICES UNAVAILABLE');assert.equal(app.nodes.get('wallet-unpriced-count').textContent,'1');assert.equal(app.nodes.get('wallet-coverage-meter').value,0);assert.equal(app.nodes.get('priced-total').textContent,'Unavailable');});
test('all returned nonzero assets can be priced and a failed refresh clears coverage',async()=>{const address='11111111111111111111111111111111';let fail=false;const app=setup(async()=>({ok:!fail,status:fail?503:200,json:async()=>fail?{error:'Unavailable'}:{address,sol:'1',tokens:[],tokenAccounts:0,observedAt:new Date().toISOString(),pricing:{prices:{So11111111111111111111111111111111111111112:{usdPrice:100}}}}}));app.nodes.get('wallet-address').value=address;await app.submit();assert.equal(app.nodes.get('wallet-price-status').textContent,'ALL RETURNED HOLDINGS PRICED');assert.equal(app.nodes.get('wallet-coverage-meter').max,1);assert.equal(app.nodes.get('wallet-coverage-meter').value,1);fail=true;await app.submit();assert.equal(app.nodes.get('wallet-price-status').textContent,'WAITING FOR BALANCES');assert.equal(app.nodes.get('wallet-coverage-meter').hidden,true);assert.equal(app.nodes.get('wallet-priced-count').textContent,'—');});

test('tiny priced holdings remain visibly nonzero in the allocation graph',async()=>{const address='11111111111111111111111111111111';const app=setup(async()=>({ok:true,status:200,json:async()=>({address,sol:'0.000001',tokens:[],tokenAccounts:0,observedAt:new Date().toISOString(),pricing:{prices:{So11111111111111111111111111111111111111112:{usdPrice:100}}}})}));app.nodes.get('wallet-address').value=address;await app.submit();assert.equal(app.nodes.get('priced-total').textContent,'< $0.01');assert.match(app.nodes.get('holdings-graph').children[0].children[0].textContent,/< \$0\.01/);});

test('allocation labels distinguish tiny nonzero shares from zero and rounded dominant shares from all',async()=>{const address='11111111111111111111111111111111';const solMint='So11111111111111111111111111111111111111112';const app=setup(async()=>({ok:true,status:200,json:async()=>({address,sol:'1',tokens:[{mint:'tiny',symbol:'USDC',quantity:'0.000001'}],tokenAccounts:1,observedAt:new Date().toISOString(),pricing:{prices:{[solMint]:{usdPrice:100},tiny:{usdPrice:1}}}})}));app.nodes.get('wallet-address').value=address;await app.submit();const bars=app.nodes.get('holdings-graph').children;assert.match(bars[0].children[0].textContent,/> 99.9%/);assert.match(bars[1].children[0].textContent,/< 0.1%/);assert.ok(bars[1].children[1].value>0);assert.equal(app.nodes.get('wallet-priced-count').textContent,'2');});
test('history orders distinct observations by timestamp when a later request carries an earlier timestamp',async()=>{const address='11111111111111111111111111111111';const observations=[{sol:'1',observedAt:'2026-10-08T16:00:20.000Z'},{sol:'2',observedAt:'2026-10-08T16:00:10.000Z'},{sol:'3',observedAt:'2026-10-08T16:00:30.000Z'}];let i=0;const app=setup(async()=>({ok:true,status:200,json:async()=>({address,...observations[i++],tokens:[],tokenAccounts:0})}));app.nodes.get('wallet-address').value=address;await app.submit();await app.submit();await app.submit();const rows=app.nodes.get('balance-history-rows').children;assert.equal(rows[0].children[1].textContent,'2 SOL');assert.equal(rows[1].children[1].textContent,'1 SOL');assert.equal(rows[2].children[1].textContent,'3 SOL');assert.equal(app.nodes.get('balance-history-plot').children[0].children[0].attributes.points,'10.00,70.00 200.00,120.00 390.00,20.00');});
