const {test}=require('node:test');const assert=require('node:assert/strict');const {readFileSync}=require('node:fs');const {runInNewContext}=require('node:vm');
const source=readFileSync(require('node:path').join(__dirname,'../assets/federation/fed-deck.js'),'utf8');
function setup(fetch,passport,timers={setTimeout,clearTimeout}){const nodes=new Map();function node(){return {textContent:'',value:'',disabled:false,children:[],events:{},attributes:{},setAttribute(k,v){this.attributes[k]=v;},addEventListener(k,f){this.events[k]=f;},append(c){this.children.push(c);if(!this.firstChild)this.firstChild=c;},replaceChildren(){this.children=[];}};}const document={getElementById(id){if(!nodes.has(id))nodes.set(id,node());return nodes.get(id);},createElement:node,createElementNS:node};runInNewContext(source,{document,fetch,AbortController,Date,setTimeout:timers.setTimeout,clearTimeout:timers.clearTimeout,globalThis:{FederationPassport:passport}});return {nodes,submit:()=>nodes.get('wallet-form').events.submit({preventDefault(){}}),clear:()=>nodes.get('wallet-clear').events.click()};}
test('invalid input never sends a lookup',async()=>{let calls=0;const app=setup(async()=>{calls++;});app.nodes.get('wallet-address').value='seed phrase is never a wallet address';await app.submit();assert.equal(calls,0);assert.equal(app.nodes.get('wallet-rows').children.length,0);});
test('lookup omits credentials and clear prevents a late response restoring balances',async()=>{let resolve;const app=setup((url,options)=>{assert.equal(url,'/api/federation-wallet');assert.equal(options.credentials,'omit');return new Promise(r=>resolve=r);});app.nodes.get('wallet-address').value='11111111111111111111111111111111';const pending=app.submit();app.clear();resolve({ok:true,status:200,json:async()=>({address:'11111111111111111111111111111111',sol:'1',tokens:[],tokenAccounts:0,observedAt:new Date().toISOString()})});await pending;assert.equal(app.nodes.get('wallet-rows').children.length,0);assert.equal(app.nodes.get('wallet-address').value,'');assert.equal(app.nodes.get('wallet-state').textContent,'No address loaded');});
test('upstream failures clear previous data and cannot masquerade as zero',async()=>{const app=setup(async()=>({ok:false,status:503,json:async()=>({error:'Service unavailable'})}));app.nodes.get('wallet-address').value='11111111111111111111111111111111';app.nodes.get('wallet-rows').children=[{}];await app.submit();assert.equal(app.nodes.get('wallet-rows').children.length,0);assert.equal(app.nodes.get('wallet-message').textContent,'Service unavailable');assert.equal(app.nodes.get('wallet-count').textContent,'—');});
test('priced allocation excludes unpriced tokens but retains their quantities',async()=>{const address='11111111111111111111111111111111';const app=setup(async()=>({ok:true,status:200,json:async()=>({address,sol:'2',tokens:[{mint:'unpriced-mint',symbol:'GFOF',quantity:'500'}],tokenAccounts:1,observedAt:new Date().toISOString(),pricing:{status:'available',prices:{So11111111111111111111111111111111111111112:{usdPrice:100,blockId:123}}}})}));app.nodes.get('wallet-address').value=address;await app.submit();assert.equal(app.nodes.get('priced-total').textContent,'$200.00');assert.match(app.nodes.get('price-coverage').textContent,/1 assets priced; 1 nonzero assets excluded/);assert.equal(app.nodes.get('wallet-rows').children.length,2);assert.equal(app.nodes.get('wallet-rows').children[1].children[1].textContent,'500');assert.equal(app.nodes.get('holdings-graph').children.length,1);assert.equal(app.nodes.get('holdings-graph').children[0].children[1].value,1);});

test('mission panel reads optional passport without writing or making network requests',()=>{let done=['repair-the-shuttle','repair-the-shuttle','unknown'];const passport={missions:[['repair-the-shuttle','Repair the Shuttle','Sera','Prepared explorer'],['the-signal','The Signal','Oryn','Signal seeker']],read:()=>({enabled:true,available:true,done}),write:()=>{throw Error('must not write');}};const app=setup(()=>{throw Error('must not fetch');},passport);assert.equal(app.nodes.get('explorer-rank').textContent,'1 / 2');assert.equal(app.nodes.get('mission-progress').value,1);assert.equal(app.nodes.get('next-mission').href,'/journey/the-signal.html');assert.equal(app.nodes.get('mission-collection').children.length,2);done.push('the-signal');app.nodes.get('mission-refresh').events.click();assert.equal(app.nodes.get('explorer-rank').textContent,'2 / 2');});
test('unavailable passport storage is shown as unknown instead of completed or empty',()=>{const passport={missions:[['repair-the-shuttle','Repair','Sera','Prepared explorer']],read:()=>({enabled:false,available:false,done:[]})};const app=setup(()=>{throw Error('must not fetch');},passport);assert.equal(app.nodes.get('explorer-rank').textContent,'Progress unavailable');assert.match(app.nodes.get('mission-message').textContent,/storage is unavailable/);assert.equal(app.nodes.get('mission-collection').children[0].children[0].textContent,'STATUS UNAVAILABLE');});

test('history uses actual same-address observations and Clear removes them',async()=>{let count=0;const address='11111111111111111111111111111111';const app=setup(async()=>({ok:true,status:200,json:async()=>({address,sol:String(++count),tokens:[],tokenAccounts:0,observedAt:new Date(1700000000000+count*1000).toISOString()})}));app.nodes.get('wallet-address').value=address;await app.submit();await app.submit();assert.equal(app.nodes.get('balance-history-rows').children.length,2);assert.equal(app.nodes.get('balance-history-plot').children.length,1);assert.match(app.nodes.get('balance-history-message').textContent,/not investment profit/);app.clear();assert.equal(app.nodes.get('balance-history-rows').children.length,0);});
test('history does not mix addresses or preserve readings after a failed lookup',async()=>{let fail=false;const app=setup(async(url,o)=>({ok:!fail,status:fail?503:200,json:async()=>fail?{error:'Unavailable'}:{address:JSON.parse(o.body).address,sol:'1',tokens:[],tokenAccounts:0,observedAt:new Date().toISOString()}}));app.nodes.get('wallet-address').value='11111111111111111111111111111111';await app.submit();app.nodes.get('wallet-address').value='Dc9CeuctqvP947ipnCJb8fSf6HhNWDooAQxsVHj2RNBV';await app.submit();assert.equal(app.nodes.get('balance-history-rows').children.length,1);fail=true;await app.submit();assert.equal(app.nodes.get('balance-history-rows').children.length,0);});

test('Clear during response decoding cannot restore stale balances or history',async()=>{let decode;const address='11111111111111111111111111111111';const app=setup(async()=>({ok:true,status:200,json:()=>new Promise(resolve=>decode=resolve)}));app.nodes.get('wallet-address').value=address;const pending=app.submit();await new Promise(setImmediate);app.clear();decode({address,sol:'1',tokens:[],tokenAccounts:0,observedAt:new Date().toISOString()});await pending;assert.equal(app.nodes.get('wallet-rows').children.length,0);assert.equal(app.nodes.get('balance-history-rows').children.length,0);assert.equal(app.nodes.get('wallet-state').textContent,'No address loaded');});
test('editing an address cancels in-flight decoding and clears the previous address display',async()=>{let decode;const address='11111111111111111111111111111111';const app=setup(async()=>({ok:true,status:200,json:()=>new Promise(resolve=>decode=resolve)}));app.nodes.get('wallet-address').value=address;const pending=app.submit();await new Promise(setImmediate);app.nodes.get('wallet-address').value='Dc9CeuctqvP947ipnCJb8fSf6HhNWDooAQxsVHj2RNBV';app.nodes.get('wallet-address').events.input();decode({address,sol:'1',tokens:[],tokenAccounts:0,observedAt:new Date().toISOString()});await pending;assert.equal(app.nodes.get('wallet-rows').children.length,0);assert.equal(app.nodes.get('wallet-load').disabled,false);});

test('a stuck lookup reaches the deadline and releases the button',async()=>{let expire,cleared=0;const app=setup((url,o)=>new Promise((resolve,reject)=>o.signal.addEventListener('abort',()=>reject(Object.assign(Error('abort'),{name:'AbortError'})))),undefined,{setTimeout(callback,delay){assert.equal(delay,20000);expire=callback;return 1;},clearTimeout(){cleared++;}});app.nodes.get('wallet-address').value='11111111111111111111111111111111';const pending=app.submit();expire();await pending;assert.match(app.nodes.get('wallet-message').textContent,/timed out/);assert.equal(app.nodes.get('wallet-load').disabled,false);assert.equal(cleared,1);assert.equal(app.nodes.get('wallet-rows').children.length,0);});

test('price coverage uses nonzero asset count rather than quantities and resets on Clear',async()=>{const address='11111111111111111111111111111111';const app=setup(async()=>({ok:true,status:200,json:async()=>({address,sol:'2',tokens:[{mint:'unpriced',quantity:'999999999'}],tokenAccounts:1,observedAt:new Date().toISOString(),pricing:{prices:{So11111111111111111111111111111111111111112:{usdPrice:100}}}})}));app.nodes.get('wallet-address').value=address;await app.submit();assert.equal(app.nodes.get('wallet-price-status').textContent,'PARTIAL PRICE COVERAGE');assert.equal(app.nodes.get('wallet-priced-count').textContent,'1');assert.equal(app.nodes.get('wallet-unpriced-count').textContent,'1');assert.equal(app.nodes.get('wallet-coverage-meter').max,2);assert.equal(app.nodes.get('wallet-coverage-meter').value,1);assert.match(app.nodes.get('wallet-coverage-label').textContent,/by asset count/);app.clear();assert.equal(app.nodes.get('wallet-priced-count').textContent,'—');assert.equal(app.nodes.get('wallet-unpriced-count').textContent,'—');assert.equal(app.nodes.get('wallet-coverage-meter').hidden,true);});
test('zero balances and a price outage have distinct coverage states without claiming completeness',async()=>{const address='11111111111111111111111111111111';let sol='0';const app=setup(async()=>({ok:true,status:200,json:async()=>({address,sol,tokens:[],tokenAccounts:0,observedAt:new Date().toISOString(),pricing:{status:'unavailable',prices:{}}})}));app.nodes.get('wallet-address').value=address;await app.submit();assert.equal(app.nodes.get('wallet-price-status').textContent,'NO NONZERO HOLDINGS');assert.equal(app.nodes.get('wallet-coverage-meter').hidden,true);sol='1';await app.submit();assert.equal(app.nodes.get('wallet-price-status').textContent,'PRICES UNAVAILABLE');assert.equal(app.nodes.get('wallet-unpriced-count').textContent,'1');assert.equal(app.nodes.get('wallet-coverage-meter').value,0);assert.equal(app.nodes.get('priced-total').textContent,'Unavailable');});
test('all returned nonzero assets can be priced and a failed refresh clears coverage',async()=>{const address='11111111111111111111111111111111';let fail=false;const app=setup(async()=>({ok:!fail,status:fail?503:200,json:async()=>fail?{error:'Unavailable'}:{address,sol:'1',tokens:[],tokenAccounts:0,observedAt:new Date().toISOString(),pricing:{prices:{So11111111111111111111111111111111111111112:{usdPrice:100}}}}}));app.nodes.get('wallet-address').value=address;await app.submit();assert.equal(app.nodes.get('wallet-price-status').textContent,'ALL RETURNED HOLDINGS PRICED');assert.equal(app.nodes.get('wallet-coverage-meter').max,1);assert.equal(app.nodes.get('wallet-coverage-meter').value,1);fail=true;await app.submit();assert.equal(app.nodes.get('wallet-price-status').textContent,'WAITING FOR BALANCES');assert.equal(app.nodes.get('wallet-coverage-meter').hidden,true);assert.equal(app.nodes.get('wallet-priced-count').textContent,'—');});

test('tiny priced holdings remain visibly nonzero in the allocation graph',async()=>{const address='11111111111111111111111111111111';const app=setup(async()=>({ok:true,status:200,json:async()=>({address,sol:'0.000001',tokens:[],tokenAccounts:0,observedAt:new Date().toISOString(),pricing:{prices:{So11111111111111111111111111111111111111112:{usdPrice:100}}}})}));app.nodes.get('wallet-address').value=address;await app.submit();assert.equal(app.nodes.get('priced-total').textContent,'< $0.01');assert.match(app.nodes.get('holdings-graph').children[0].children[0].textContent,/< \$0\.01/);});

test('allocation labels distinguish tiny nonzero shares from zero and rounded dominant shares from all',async()=>{const address='11111111111111111111111111111111';const solMint='So11111111111111111111111111111111111111112';const app=setup(async()=>({ok:true,status:200,json:async()=>({address,sol:'1',tokens:[{mint:'tiny',symbol:'USDC',quantity:'0.000001'}],tokenAccounts:1,observedAt:new Date().toISOString(),pricing:{prices:{[solMint]:{usdPrice:100},tiny:{usdPrice:1}}}})}));app.nodes.get('wallet-address').value=address;await app.submit();const bars=app.nodes.get('holdings-graph').children;assert.match(bars[0].children[0].textContent,/> 99.9%/);assert.match(bars[1].children[0].textContent,/< 0.1%/);assert.ok(bars[1].children[1].value>0);assert.equal(app.nodes.get('wallet-priced-count').textContent,'2');});
test('history orders distinct observations by timestamp when a later request carries an earlier timestamp',async()=>{const address='11111111111111111111111111111111';const observations=[{sol:'1',observedAt:'2026-10-08T16:00:20.000Z'},{sol:'2',observedAt:'2026-10-08T16:00:10.000Z'},{sol:'3',observedAt:'2026-10-08T16:00:30.000Z'}];let i=0;const app=setup(async()=>({ok:true,status:200,json:async()=>({address,...observations[i++],tokens:[],tokenAccounts:0})}));app.nodes.get('wallet-address').value=address;await app.submit();await app.submit();await app.submit();const rows=app.nodes.get('balance-history-rows').children;assert.equal(rows[0].children[1].textContent,'2 SOL');assert.equal(rows[1].children[1].textContent,'1 SOL');assert.equal(rows[2].children[1].textContent,'3 SOL');assert.equal(app.nodes.get('balance-history-plot').children[0].children[0].attributes.points,'10.00,70.00 200.00,120.00 390.00,20.00');});

test('a token Lens link passes only its mint and opens separately even when its price is unavailable',async()=>{const address='DqtrauD2dDNB2v38cG9xVsDYxjwT1hwVV6aGRLwsPcd6',mint='Dc9CeuctqvP947ipnCJb8fSf6HhNWDooAQxsVHj2RNBV';let calls=0;const app=setup(async()=>{calls++;return {ok:true,status:200,json:async()=>({address,sol:'1',tokens:[{mint,symbol:'GFOF',quantity:'50'}],tokenAccounts:1,observedAt:new Date().toISOString()})};});app.nodes.get('wallet-address').value=address;await app.submit();const rows=app.nodes.get('wallet-rows').children;assert.equal(rows[0].children[0].children.length,0);const link=rows[1].children[0].children[1];assert.equal(link.href,'https://dossiertrack.co/token-structure?mint='+mint);assert.ok(!link.href.includes(address));assert.equal(link.target,'_blank');assert.equal(link.rel,'noopener noreferrer');assert.match(link.attributes['aria-label'],/opens a new tab/);assert.equal(calls,1);app.clear();assert.equal(app.nodes.get('wallet-rows').children.length,0);});
test('malformed or wrong-byte-length mint data cannot create a Lens lookup link',async()=>{const address='11111111111111111111111111111111';const app=setup(async()=>({ok:true,status:200,json:async()=>({address,sol:'0',tokens:[{mint:'javascript:alert(1)',quantity:'1'},{mint:'1'.repeat(33),quantity:'2'}],tokenAccounts:2,observedAt:new Date().toISOString()})}));app.nodes.get('wallet-address').value=address;await app.submit();for(const row of app.nodes.get('wallet-rows').children.slice(1))assert.equal(row.children[0].children.length,1);});

test('wallet source details preserve each confirmed slot and link the viewed public address without a lookup',async()=>{const address='DqtrauD2dDNB2v38cG9xVsDYxjwT1hwVV6aGRLwsPcd6';let calls=0;const app=setup(async()=>{calls++;return {ok:true,status:200,json:async()=>({address,sol:'1',tokens:[],tokenAccounts:0,observedAt:new Date().toISOString(),commitment:'confirmed',slots:[100,102,101]})};});app.nodes.get('wallet-address').value=address;await app.submit();assert.equal(app.nodes.get('wallet-source-panel').hidden,false);const link=app.nodes.get('wallet-source-links').children[0];assert.equal(link.href,'https://explorer.solana.com/address/'+address);assert.equal(link.target,'_blank');assert.equal(link.rel,'noopener noreferrer');assert.match(app.nodes.get('wallet-source-message').textContent,/not one atomic or finalized snapshot/);assert.deepEqual(app.nodes.get('wallet-source-slots').children.filter((_,i)=>i%2).map(n=>n.textContent),['Slot 100','Slot 102','Slot 101']);assert.equal(calls,1);app.clear();assert.equal(app.nodes.get('wallet-source-panel').hidden,true);assert.equal(app.nodes.get('wallet-source-links').children.length,0);assert.equal(app.nodes.get('wallet-source-slots').children.length,0);});
test('missing, malformed or differently committed metadata never claims confirmed source slots',async()=>{const address='11111111111111111111111111111111';for(const metadata of [{},{commitment:'finalized',slots:[1,2,3]},{commitment:'confirmed',slots:[1,2]},{commitment:'confirmed',slots:[1,-1,3]},{commitment:'confirmed',slots:[1,2,9007199254740992]}]){const app=setup(async()=>({ok:true,status:200,json:async()=>({address,sol:'1',tokens:[],tokenAccounts:0,observedAt:new Date().toISOString(),...metadata})}));app.nodes.get('wallet-address').value=address;await app.submit();assert.match(app.nodes.get('wallet-source-message').textContent,/unavailable/);assert.equal(app.nodes.get('wallet-source-slots').children.length,0);assert.equal(app.nodes.get('wallet-source-links').children.length,1);}});
test('address edits remove the previous Explorer destination and source evidence immediately',async()=>{const address='11111111111111111111111111111111';const app=setup(async()=>({ok:true,status:200,json:async()=>({address,sol:'1',tokens:[],tokenAccounts:0,observedAt:new Date().toISOString(),commitment:'confirmed',slots:[1,2,3]})}));app.nodes.get('wallet-address').value=address;await app.submit();app.nodes.get('wallet-address').value='different';app.nodes.get('wallet-address').events.input();assert.equal(app.nodes.get('wallet-source-panel').hidden,true);assert.equal(app.nodes.get('wallet-source-links').children.length,0);assert.equal(app.nodes.get('wallet-source-slots').children.length,0);});

test('deadline settles the wallet UI even when fetch never honors abort', {timeout:1000},async()=>{let expire,cleared=0;const app=setup(()=>new Promise(()=>{}),undefined,{setTimeout(callback,delay){assert.equal(delay,20000);expire=callback;return 1;},clearTimeout(){cleared++;}});app.nodes.get('wallet-address').value='11111111111111111111111111111111';const pending=app.submit();expire();await pending;assert.equal(app.nodes.get('wallet-load').disabled,false);assert.match(app.nodes.get('wallet-message').textContent,/timed out/);assert.equal(app.nodes.get('wallet-source-panel').hidden,true);assert.equal(cleared,1);});
test('late response decoding after timeout cannot restore balances or overwrite a successful retry',{timeout:1000},async()=>{const address='11111111111111111111111111111111';let decode,expire,calls=0;const app=setup(async()=>({ok:true,status:200,json:++calls===1?()=>new Promise(resolve=>decode=resolve):async()=>({address,sol:'2',tokens:[],tokenAccounts:0,observedAt:new Date().toISOString(),commitment:'confirmed',slots:[1,2,3]})}),undefined,{setTimeout(callback){expire=callback;return 1;},clearTimeout(){}});app.nodes.get('wallet-address').value=address;const pending=app.submit();await new Promise(setImmediate);expire();await pending;assert.equal(app.nodes.get('wallet-rows').children.length,0);assert.equal(app.nodes.get('wallet-load').disabled,false);await app.submit();decode({address,sol:'99',tokens:[],tokenAccounts:0,observedAt:new Date().toISOString()});await new Promise(setImmediate);assert.equal(app.nodes.get('wallet-rows').children[0].children[1].textContent,'2');assert.equal(app.nodes.get('balance-history-rows').children.length,1);assert.equal(app.nodes.get('wallet-source-slots').children.length,6);assert.equal(app.nodes.get('wallet-state').textContent,'Address loaded');});
test('Clear settles an ignored-abort lookup immediately and preserves its cleared message',{timeout:1000},async()=>{let cleared=0;const app=setup(()=>new Promise(()=>{}),undefined,{setTimeout(){return 1;},clearTimeout(){cleared++;}});app.nodes.get('wallet-address').value='11111111111111111111111111111111';const pending=app.submit();app.clear();await pending;assert.equal(cleared,1);assert.equal(app.nodes.get('wallet-load').disabled,false);assert.match(app.nodes.get('wallet-message').textContent,/Cleared from this page/);assert.equal(app.nodes.get('wallet-rows').children.length,0);assert.equal(app.nodes.get('wallet-source-panel').hidden,true);});

test('asset filtering matches symbols and mint fragments without changing totals or requesting data',async()=>{
 const address='11111111111111111111111111111111',mint='Dc9CeuctqvP947ipnCJb8fSf6HhNWDooAQxsVHj2RNBV';let calls=0;
 const app=setup(async()=>{calls++;return {ok:true,status:200,json:async()=>({address,sol:'2',tokens:[{mint,symbol:'GFOF',quantity:'500'},{mint:'unknown-mint',symbol:null,quantity:'7'}],tokenAccounts:2,observedAt:new Date().toISOString(),pricing:{prices:{So11111111111111111111111111111111111111112:{usdPrice:100}}}})};});
 app.nodes.get('wallet-address').value=address;await app.submit();
 const filter=app.nodes.get('wallet-asset-filter'),rows=app.nodes.get('wallet-rows').children;
 assert.equal(app.nodes.get('wallet-filter-panel').hidden,false);
 for(const [query,expected] of [['  gFoF  ',[true,false,true]],['dC9Ceu',[true,false,true]],['SOL',[false,true,true]],['Unverified',[true,true,false]],['not present',[true,true,true]]]){
  filter.value=query;filter.events.input();assert.deepEqual(rows.map(r=>r.hidden),expected);
  assert.equal(app.nodes.get('priced-total').textContent,'$200.00');assert.equal(app.nodes.get('wallet-count').textContent,'2');assert.equal(app.nodes.get('holdings-graph').children.length,1);
 }
 assert.match(app.nodes.get('wallet-filter-status').textContent,/No matching assets/);
 app.nodes.get('wallet-filter-clear').events.click();assert.equal(filter.value,'');assert.deepEqual(rows.map(r=>r.hidden),[false,false,false]);
 assert.match(app.nodes.get('wallet-filter-status').textContent,/Showing 3 of 3 assets/);assert.equal(calls,1);
});
test('asset filters cannot persist across edits, clear or a failed refresh',async()=>{
 const address='11111111111111111111111111111111';let fail=false;
 const app=setup(async()=>({ok:!fail,status:fail?503:200,json:async()=>fail?{error:'Unavailable'}:{address,sol:'1',tokens:[],tokenAccounts:0,observedAt:new Date().toISOString()}}));
 for(const action of ['edit','clear','failure']){
  fail=false;app.nodes.get('wallet-address').value=address;await app.submit();
  const filter=app.nodes.get('wallet-asset-filter');filter.value='missing';filter.events.input();
  if(action==='edit')app.nodes.get('wallet-address').events.input();
  if(action==='clear')app.clear();
  if(action==='failure'){fail=true;await app.submit();}
  assert.equal(filter.value,'');assert.equal(app.nodes.get('wallet-filter-panel').hidden,true);assert.equal(app.nodes.get('wallet-rows').children.length,0);
  assert.equal(app.nodes.get('wallet-filter-status').textContent,'Read balances to filter returned assets.');
 }
});
