import {test} from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
const code=readFileSync(new URL('../journey/passport.js',import.meta.url),'utf8');
function boot(local=new Map(),session=new Map(),blocked=false){const storage=map=>({getItem(k){if(blocked)throw Error();return map.get(k)||null;},setItem(k,v){if(blocked)throw Error();map.set(k,v);},removeItem(k){if(blocked)throw Error();map.delete(k);}});const c={localStorage:storage(local),sessionStorage:storage(session)};vm.runInNewContext(code,c);return {p:c.FederationPassport,local,session};}
test('passport requires explicit opt-in; completion then survives a fresh session',()=>{const t=boot();assert.equal(t.p.mark('repair-the-shuttle'),false);assert.equal(t.local.size,0);assert.equal(t.p.enable(),true);assert.equal(t.p.mark('repair-the-shuttle'),true);const fresh=boot(t.local);assert.deepEqual([...fresh.p.read().done],['repair-the-shuttle']);assert.equal(fresh.p.session().length,0);});
test('imports all existing session markers and ignores unknown values',()=>{const s=new Map([['gf-journey-v1','[0,0,4,-1,99,"2"]'],['gf-journey-meridian-relay-v1','complete'],['gf-journey-long-way-home-v1','started']]);const t=boot(new Map(),s);t.p.enable();assert.deepEqual([...t.p.read().done],['repair-the-shuttle','docking-request','meridian-relay']);assert.equal(t.p.mark('unknown'),false);t.p.mark('repair-the-shuttle');assert.equal(t.p.read().done.length,3);});
test('removal preserves avatar and session progress and disables future persistence',()=>{const t=boot(new Map([['gf-journey-avatar-v1','avatar']]),new Map([['gf-journey-v1','[2]']]));t.p.enable();t.p.forget();assert.equal(t.local.get('gf-journey-avatar-v1'),'avatar');assert.equal(t.session.get('gf-journey-v1'),'[2]');assert.equal(t.p.mark('meridian-relay'),false);assert.equal(t.p.read().enabled,false);});
test('blocked or corrupt storage does not break play',()=>{const t=boot(new Map(),new Map(),true);assert.equal(t.p.read().available,false);assert.equal(t.p.enable(),false);assert.equal(t.p.mark('repair-the-shuttle'),false);assert.equal(t.p.forget(),false);const c=boot(new Map([['gf-journey-passport-v1','{']]));assert.equal(c.p.read().available,false);assert.equal(c.p.enable(),true);});
test('successive tabs merge current completed missions rather than duplicate badges',()=>{const local=new Map();const a=boot(local),b=boot(local);a.p.enable();a.p.mark('repair-the-shuttle');b.p.mark('meridian-relay');a.p.mark('meridian-relay');assert.equal(a.p.read().done.length,2);});
test('every mission loads passport before its completion handler',()=>{const {p}=boot();for(const [id]of p.missions){const html=readFileSync(new URL('../journey/'+id+'.html',import.meta.url),'utf8');assert.equal((html.match(/src="passport.js\?v=1"/g)||[]).length,1);assert.ok(html.indexOf('src="passport.js')<html.lastIndexOf('<script'));}});
