import {test} from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import worker,{PriceBudget} from '../workers/price-budget-preview/worker.mjs';
import budget from '../netlify/lib/price-budget.cjs';
import prices from '../netlify/lib/wallet-prices.cjs';
function storage(){const db=new DatabaseSync(':memory:');return {db,sql:{exec(q,...args){const stmt=db.prepare(q);return {toArray:()=>stmt.all(...args)}; }},transactionSync(fn){db.exec('BEGIN');try{const x=fn();db.exec('COMMIT');return x;}catch(e){db.exec('ROLLBACK');throw e;}}};}
// Cloudflare exec performs writes eagerly; the adapter mirrors that behavior.
function fixture(){const s=storage();s.sql.exec=(q,...args)=>{const stmt=s.db.prepare(q);if(/^SELECT/.test(q))return {toArray:()=>stmt.all(...args)};stmt.run(...args);return {toArray:()=>[]};};return s;}
test('shared SQLite reservations survive object recreation and admit only 24 simultaneous callers',async()=>{const old=Date.now;Date.now=()=>100000;try{const s=fixture();const a=new PriceBudget({storage:s});const results=await Promise.all(Array.from({length:100},()=>a.fetch()));assert.equal(results.filter(r=>r.status===200).length,24);const b=new PriceBudget({storage:s});assert.equal(b.fetch().status,429);Date.now=()=>160000;assert.equal(b.fetch().status,200);assert.equal(s.db.prepare('SELECT count(*) AS n FROM budget').get().n,1);s.db.close();}finally{Date.now=old;}});
test('daily ceiling, backwards clock and malformed state deny; UTC reset retains rolling window',()=>{const old=Date.now;let now=86399990;Date.now=()=>now;try{const s=fixture();const a=new PriceBudget({storage:s});assert.equal(a.fetch().status,200);s.db.prepare('UPDATE budget SET used=3000').run();assert.equal(a.fetch().status,429);now=86400001;assert.equal(a.fetch().status,200);assert.equal(s.db.prepare('SELECT used FROM budget').get().used,1);now=80000;assert.equal(a.fetch().status,503);now=90000000;s.db.prepare("UPDATE budget SET times='bad'").run();assert.equal(a.fetch().status,503);s.db.close();}finally{Date.now=old;}});
test('worker rejects unauthenticated requests and payloads before accessing shared state',async()=>{const secret='x'.repeat(43);let calls=0;const env={BUDGET_SECRET:secret,PRICE_BUDGET:{idFromName(name){assert.equal(name,'price-preview-v1');return name;},get(){return {fetch:async()=>{calls++;return new Response('{"allowed":true}');}};}}};for(const [options,status] of [[{method:'POST'},403],[{method:'GET'},405],[{method:'POST',headers:{Authorization:'Bearer '+secret},body:'wallet'},400]]){assert.equal((await worker.fetch(new Request('https://example.test/reserve-price',options),env)).status,status);}assert.equal(calls,0);assert.equal((await worker.fetch(new Request('https://example.test/reserve-price',{method:'POST',headers:{Authorization:'Bearer '+secret}}),env)).status,200);assert.equal(calls,1);});
test('configured limiter fails closed without forwarding an address, mint or provider key',async()=>{const oldUrl=process.env.PRICE_BUDGET_URL,oldSecret=process.env.PRICE_BUDGET_SECRET;process.env.PRICE_BUDGET_URL='https://gfof-price-budget-preview.example.workers.dev/reserve-price';process.env.PRICE_BUDGET_SECRET='x'.repeat(43);try{let calls=0;const fetcher=async(url,options)=>{calls++;assert.equal(url,process.env.PRICE_BUDGET_URL);assert.equal(options.body,undefined);assert.deepEqual(Object.keys(options.headers),['Authorization']);return new Response('{"allowed":false}',{status:429});};const p=await prices.readPrices([{mint:'synthetic',decimals:6}],100,fetcher);assert.equal(p.status,'unavailable');assert.equal(calls,1);assert.equal(await budget.reservePrice(async()=>{throw Error('private details');}),false);process.env.PRICE_BUDGET_URL='https://evil.test/';calls=0;assert.equal(await budget.reservePrice(async()=>{calls++;}),false);assert.equal(calls,0);}finally{for(const [key,value] of [['PRICE_BUDGET_URL',oldUrl],['PRICE_BUDGET_SECRET',oldSecret]]){if(value===undefined)delete process.env[key];else process.env[key]=value;}}});
