-- Draft candidate only. Do not apply or attach without exact-target approval.
-- File generated by Supabase CLI 2.120.0; no hosted setting is changed here.
-- Attach while signup is closed; disable signup before any later hook rollback.
begin;
set local statement_timeout = '8s';
set local lock_timeout = '2s';

create schema federation_auth_signup;
revoke all on schema federation_auth_signup from public, anon, authenticated, service_role;

create function federation_auth_signup.google_only(event jsonb)
returns jsonb language plpgsql security invoker set search_path = ''
as $hook$
begin
  -- app_metadata is supplied by Auth, not the applicant's user_metadata.
  if event #>> '{user,app_metadata,provider}' = 'google'
     and event #> '{user,is_anonymous}' = 'false'::jsonb then
    return '{}'::jsonb;
  end if;
  return jsonb_build_object('error',jsonb_build_object(
    'http_code',403,
    'message','Account creation is unavailable for this sign-in method.'
  ));
end;
$hook$;

revoke all on function federation_auth_signup.google_only(jsonb) from public, anon, authenticated, service_role;
grant usage on schema federation_auth_signup to supabase_auth_admin;
grant execute on function federation_auth_signup.google_only(jsonb) to supabase_auth_admin;
commit;
